-- 04-check-tde-wallet.sql
SET SERVEROUTPUT ON
DECLARE
    v_status VARCHAR2(255);
BEGIN
    BEGIN
        SELECT STATUS INTO v_status FROM V$ENCRYPTION_WALLET WHERE ROWNUM = 1;
        DBMS_OUTPUT.PUT_LINE('WALLET_STATUS=' || v_status);
    EXCEPTION WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('WALLET_STATUS=NOT_CONFIGURED');
    END;
END;
/
